# fly.toml app configuration file generated for blackjack-cards on 2025-06-06T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'cards0'
primary_region = 'iad'

[build]
dockerfile = 'Dockerfile'

[env]
ASPNETCORE_ENVIRONMENT = 'Production'
ASPNETCORE_URLS = 'http://+:5001'
URL = 'cards.joebad.com'

[http_service]
internal_port = 5001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/health"

[[services]]
  internal_port = 5001
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

[services.concurrency]
  type = "requests"
  hard_limit = 25
  soft_limit = 20

dedicated_ipv4 = true

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 100

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

# Persistent volume for SQLite database
[[mounts]]
source = 'blackjack_data'
destination = '/app/data'
initial_size = '1GB'

# Restart policy
[[restart]]
policy = 'always'